server:
  servlet:
    context-path: /fabrick
  port: ${app.var.server-port}

spring:
  profiles.active: local
#  main.banner-mode: off
  datasource:
    url: jdbc:mysql://${app.var.database-host}:${app.var.database-port}/${app.var.database-name}?useSSL=false${app.var.database-params}
    username: ${app.var.database-username}
    password: ${app.var.database-password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
        ddl-auto: create
    generate-ddl: ${app.var.ddl-auto}